server:
  port: 8090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: policy-service-contrats
          uri: lb://policy-service
          predicates:
            - Path=/policys/contrats/**
          filters:
            - RewritePath=/policys/contrats/(?<segment>.*), /contrats/$\{segment}
        - id: policy-service-sinistres
          uri: lb://policy-service
          predicates:
            - Path=/policys/sinistres/**
          filters:
            - RewritePath=/policys/sinistres/(?<segment>.*), /sinistres/$\{segment}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
